### ISSUE TITLE
License file is missing from repo

### ISSUE THREAD

**Issue by publicus** [cassidoo/next-netlify-blog-starter#10]
Thank you very much for your work on this project! I'm learning a lot from it, as I build a new site.

Would you be willing to add a `LICENSE` file to this repo? It would give me extra peace of mind to know what the terms, if any, are for this code, which I'm building a new website around.

Thank you for your consideration!

**Comment by cassidoo** [comment]
Done! Thanks!

**Comment by publicus** [comment]
@cassidoo Thank you very much!
