### ISSUE TITLE
Posts list on home page are doubled

### ISSUE THREAD

**Issue by benjifriedman** [cassidoo/next-netlify-blog-starter#27]
From a fresh install. I can't tell why it's doing this.

**Comment by benjifriedman** [comment]
If it helps at all, I see the page is rendering one PostList element. But all the markdown file links are duplicated

**Comment by naoufalzerai** [comment]
I posted a fix waiting for the merge you can take a look 
https://github.com/cassidoo/next-netlify-blog-starter/pull/23

**Comment by cassidoo** [comment]
Thank you for fixing it!
